/**
 * BJCP-style numeric target ranges for common beer styles.
 *
 * These are the vital-statistic ranges (OG, FG, IBU, SRM color, ABV) --
 * factual numeric reference data of the kind published across the
 * brewing community (BJCP guidelines, brewing software, homebrew club
 * references) for these well-known style categories. The style names
 * and numeric ranges reflect commonly published figures; the
 * descriptions below are original one-line summaries written for this
 * app, not copied from the BJCP guidelines document's descriptive text.
 * For full style guidance (history, appearance, flavor, commercial
 * examples), always consult the official BJCP Style Guidelines
 * (bjcp.org) -- this is a quick numeric reference only.
 *
 * COVERAGE: this list aims to cover every BJCP 2021 beer subcategory
 * that has a fixed numeric vital-statistics range. It intentionally
 * excludes the "open" / freeform categories (Category 27 Historical
 * Beer, 29-34 Fruit/Spiced/Alternative-Fermentable/Wood/Smoked/
 * Specialty Beer, and Mead/Cider categories) because those are
 * explicitly defined by BJCP as inheriting from a base style or having
 * no fixed range -- inventing numbers for them would be actively wrong,
 * not just approximate. Numeric ranges reconstructed from general
 * brewing knowledge; verify anything competition-relevant against the
 * official guidelines document.
 */

export interface RangeMinMax {
  min: number;
  max: number;
}

export interface BjcpStyleRange {
  id: string;
  name: string;
  category: string;
  description: string;
  og: RangeMinMax;
  fg: RangeMinMax;
  ibu: RangeMinMax;
  srm: RangeMinMax;
  abvPercent: RangeMinMax;
}

export const BJCP_STYLES: BjcpStyleRange[] = [
  {
    id: 'american-light-lager',
    name: 'American Light Lager',
    category: 'Standard American Beer',
    description: 'Very pale, light-bodied, highly attenuated, minimal hop character.',
    og: { min: 1.028, max: 1.04 },
    fg: { min: 0.998, max: 1.008 },
    ibu: { min: 8, max: 12 },
    srm: { min: 2, max: 3 },
    abvPercent: { min: 2.8, max: 4.2 },
  },
  {
    id: 'american-lager',
    name: 'American Lager',
    category: 'Standard American Beer',
    description: 'Pale, crisp, well-attenuated lager with subtle hop bitterness.',
    og: { min: 1.04, max: 1.05 },
    fg: { min: 1.004, max: 1.01 },
    ibu: { min: 8, max: 18 },
    srm: { min: 2, max: 4 },
    abvPercent: { min: 4.2, max: 5.3 },
  },
  {
    id: 'czech-pilsner',
    name: 'Czech Premium Pale Lager (Pilsner)',
    category: 'Czech Lager',
    description: 'Golden, malty-yet-crisp lager with pronounced Saaz hop character.',
    og: { min: 1.044, max: 1.06 },
    fg: { min: 1.013, max: 1.017 },
    ibu: { min: 30, max: 45 },
    srm: { min: 3.5, max: 6 },
    abvPercent: { min: 4.2, max: 5.8 },
  },
  {
    id: 'german-pilsner',
    name: 'German Pils',
    category: 'Pale Bitter European Beer',
    description: 'Pale, dry, highly-attenuated lager with firm, clean hop bitterness.',
    og: { min: 1.044, max: 1.05 },
    fg: { min: 1.008, max: 1.013 },
    ibu: { min: 22, max: 40 },
    srm: { min: 2, max: 5 },
    abvPercent: { min: 4.4, max: 5.2 },
  },
  {
    id: 'munich-helles',
    name: 'Munich Helles',
    category: 'Amber Malty European Beer',
    description: 'Soft, malty-sweet golden lager with restrained noble hop bitterness.',
    og: { min: 1.045, max: 1.051 },
    fg: { min: 1.008, max: 1.012 },
    ibu: { min: 16, max: 22 },
    srm: { min: 3, max: 5 },
    abvPercent: { min: 4.7, max: 5.4 },
  },
  {
    id: 'vienna-lager',
    name: 'Vienna Lager',
    category: 'Amber Malty European Beer',
    description: 'Toasty amber lager with moderate malt sweetness and clean hop balance.',
    og: { min: 1.045, max: 1.055 },
    fg: { min: 1.01, max: 1.014 },
    ibu: { min: 18, max: 30 },
    srm: { min: 9, max: 15 },
    abvPercent: { min: 4.5, max: 5.5 },
  },
  {
    id: 'oktoberfest-marzen',
    name: 'Oktoberfestbier / Marzen',
    category: 'Amber Malty European Beer',
    description: 'Rich, toasty amber-to-copper lager, malt-forward with clean finish.',
    og: { min: 1.054, max: 1.057 },
    fg: { min: 1.01, max: 1.014 },
    ibu: { min: 18, max: 24 },
    srm: { min: 8, max: 17 },
    abvPercent: { min: 5.8, max: 6.3 },
  },
  {
    id: 'american-pale-ale',
    name: 'American Pale Ale',
    category: 'Pale American Ale',
    description: 'Balanced, moderately hoppy pale ale with citrusy/piney American hop character.',
    og: { min: 1.045, max: 1.06 },
    fg: { min: 1.01, max: 1.015 },
    ibu: { min: 30, max: 50 },
    srm: { min: 5, max: 10 },
    abvPercent: { min: 4.5, max: 6.2 },
  },
  {
    id: 'english-bitter',
    name: 'Ordinary Bitter',
    category: 'British Bitter',
    description: 'Low-strength, malt-balanced English session ale with earthy hop character.',
    og: { min: 1.03, max: 1.039 },
    fg: { min: 1.007, max: 1.011 },
    ibu: { min: 25, max: 35 },
    srm: { min: 8, max: 14 },
    abvPercent: { min: 3.2, max: 3.8 },
  },
  {
    id: 'esb',
    name: 'Strong Bitter (ESB)',
    category: 'British Bitter',
    description: 'Robust, malt-forward English ale with balanced earthy hop bitterness.',
    og: { min: 1.048, max: 1.06 },
    fg: { min: 1.01, max: 1.016 },
    ibu: { min: 30, max: 50 },
    srm: { min: 8, max: 18 },
    abvPercent: { min: 4.6, max: 6.2 },
  },
  {
    id: 'american-amber-ale',
    name: 'American Amber Ale',
    category: 'Amber and Brown American Beer',
    description: 'Caramel-malty amber ale with moderate American hop bitterness/aroma.',
    og: { min: 1.045, max: 1.06 },
    fg: { min: 1.01, max: 1.015 },
    ibu: { min: 25, max: 40 },
    srm: { min: 10, max: 17 },
    abvPercent: { min: 4.5, max: 6.2 },
  },
  {
    id: 'brown-ale',
    name: 'American Brown Ale',
    category: 'Amber and Brown American Beer',
    description: 'Malty brown ale with roast/chocolate notes and moderate hop bitterness.',
    og: { min: 1.045, max: 1.06 },
    fg: { min: 1.01, max: 1.016 },
    ibu: { min: 20, max: 40 },
    srm: { min: 18, max: 35 },
    abvPercent: { min: 4.3, max: 6.2 },
  },
  {
    id: 'porter',
    name: 'American Porter',
    category: 'Brown British Beer / American Porter',
    description: 'Dark, roasty ale with chocolate/coffee notes, moderate bitterness.',
    og: { min: 1.05, max: 1.07 },
    fg: { min: 1.012, max: 1.018 },
    ibu: { min: 20, max: 40 },
    srm: { min: 22, max: 35 },
    abvPercent: { min: 4.8, max: 6.5 },
  },
  {
    id: 'dry-irish-stout',
    name: 'Irish Stout',
    category: 'Strong British Ale / Stout',
    description: 'Dry, roasty, coffee-like dark ale with restrained sweetness.',
    og: { min: 1.036, max: 1.044 },
    fg: { min: 1.007, max: 1.011 },
    ibu: { min: 25, max: 45 },
    srm: { min: 25, max: 40 },
    abvPercent: { min: 4.0, max: 4.5 },
  },
  {
    id: 'sweet-stout',
    name: 'Sweet Stout',
    category: 'Strong British Ale / Stout',
    description: 'Dark, full-bodied, sweet stout with roasty malt and low bitterness.',
    og: { min: 1.044, max: 1.06 },
    fg: { min: 1.012, max: 1.024 },
    ibu: { min: 20, max: 40 },
    srm: { min: 30, max: 40 },
    abvPercent: { min: 4.0, max: 6.0 },
  },
  {
    id: 'imperial-stout',
    name: 'Imperial Stout',
    category: 'Strong British Ale / Stout',
    description: 'Big, rich, roasty dark ale with high alcohol warmth and complex malt.',
    og: { min: 1.075, max: 1.115 },
    fg: { min: 1.018, max: 1.03 },
    ibu: { min: 50, max: 90 },
    srm: { min: 30, max: 40 },
    abvPercent: { min: 8.0, max: 12.0 },
  },
  {
    id: 'american-ipa',
    name: 'American IPA',
    category: 'IPA',
    description: 'Assertively hoppy, moderately strong pale ale with citrus/pine/resin hop character.',
    og: { min: 1.056, max: 1.07 },
    fg: { min: 1.008, max: 1.014 },
    ibu: { min: 40, max: 70 },
    srm: { min: 6, max: 14 },
    abvPercent: { min: 5.5, max: 7.5 },
  },
  {
    id: 'hazy-ipa',
    name: 'Hazy IPA (NEIPA)',
    category: 'IPA',
    description: 'Soft, juicy, hazy IPA with intense fruit-forward hop aroma and low bitterness.',
    og: { min: 1.06, max: 1.085 },
    fg: { min: 1.01, max: 1.015 },
    ibu: { min: 25, max: 60 },
    srm: { min: 3, max: 7 },
    abvPercent: { min: 6.0, max: 9.0 },
  },
  {
    id: 'double-ipa',
    name: 'Double/Imperial IPA',
    category: 'IPA',
    description: 'Big, intensely hoppy IPA with high alcohol strength and firm bitterness.',
    og: { min: 1.065, max: 1.085 },
    fg: { min: 1.008, max: 1.018 },
    ibu: { min: 60, max: 120 },
    srm: { min: 6, max: 14 },
    abvPercent: { min: 7.5, max: 10.0 },
  },
  {
    id: 'weissbier',
    name: 'German Weissbier (Hefeweizen)',
    category: 'German Wheat Beer',
    description: 'Pale, wheat-forward ale with banana/clove yeast character, low bitterness.',
    og: { min: 1.044, max: 1.053 },
    fg: { min: 1.008, max: 1.014 },
    ibu: { min: 8, max: 15 },
    srm: { min: 2, max: 6 },
    abvPercent: { min: 4.3, max: 5.6 },
  },
  {
    id: 'witbier',
    name: 'Witbier',
    category: 'Belgian Wheat Beer',
    description: 'Pale, tangy, spiced (coriander/orange peel) Belgian wheat ale.',
    og: { min: 1.044, max: 1.052 },
    fg: { min: 1.008, max: 1.012 },
    ibu: { min: 8, max: 20 },
    srm: { min: 2, max: 4 },
    abvPercent: { min: 4.5, max: 5.5 },
  },
  {
    id: 'belgian-dubbel',
    name: 'Belgian Dubbel',
    category: 'Trappist Ale',
    description: 'Malty, dark amber Belgian ale with fruity ester and spicy phenol character.',
    og: { min: 1.062, max: 1.075 },
    fg: { min: 1.008, max: 1.018 },
    ibu: { min: 15, max: 25 },
    srm: { min: 10, max: 17 },
    abvPercent: { min: 6.0, max: 7.6 },
  },
  {
    id: 'belgian-tripel',
    name: 'Belgian Tripel',
    category: 'Trappist Ale',
    description: 'Pale, strong Belgian ale, deceptively drinkable with fruity, spicy complexity.',
    og: { min: 1.075, max: 1.085 },
    fg: { min: 1.008, max: 1.014 },
    ibu: { min: 20, max: 40 },
    srm: { min: 4.5, max: 7 },
    abvPercent: { min: 7.5, max: 9.5 },
  },
  {
    id: 'saison',
    name: 'Saison',
    category: 'Belgian/French Ale',
    description: 'Dry, highly-attenuated, peppery/fruity farmhouse ale with earthy hop notes.',
    og: { min: 1.048, max: 1.065 },
    fg: { min: 1.002, max: 1.012 },
    ibu: { min: 20, max: 35 },
    srm: { min: 5, max: 14 },
    abvPercent: { min: 5.0, max: 7.0 },
  },
  {
    id: 'berliner-weisse',
    name: 'Berliner Weisse',
    category: 'Sour Ale',
    description: 'Very pale, tart, low-alcohol wheat sour ale, refreshing and lightly fruity.',
    og: { min: 1.028, max: 1.032 },
    fg: { min: 1.003, max: 1.006 },
    ibu: { min: 3, max: 8 },
    srm: { min: 2, max: 3 },
    abvPercent: { min: 2.8, max: 3.8 },
  },
  {
    id: 'barleywine',
    name: 'English Barleywine',
    category: 'Strong Ale',
    description: 'Big, rich, malty-sweet strong ale with warming alcohol and complex fruit/toffee notes.',
    og: { min: 1.09, max: 1.12 },
    fg: { min: 1.018, max: 1.03 },
    ibu: { min: 35, max: 70 },
    srm: { min: 8, max: 22 },
    abvPercent: { min: 8.0, max: 12.0 },
  },

  // --- Category 1: Standard American Beer (remaining) ---
  {
    id: 'cream-ale',
    name: 'Cream Ale',
    category: 'Standard American Beer',
    description: 'Pale, light-bodied, crisp American ale, lager-like in character.',
    og: { min: 1.042, max: 1.055 },
    fg: { min: 1.006, max: 1.012 },
    ibu: { min: 8, max: 20 },
    srm: { min: 2.5, max: 5 },
    abvPercent: { min: 4.2, max: 5.6 },
  },
  {
    id: 'american-wheat-beer',
    name: 'American Wheat Beer',
    category: 'Standard American Beer',
    description: 'Pale, clean American wheat ale, crisp with neutral yeast character.',
    og: { min: 1.04, max: 1.055 },
    fg: { min: 1.008, max: 1.013 },
    ibu: { min: 15, max: 30 },
    srm: { min: 3, max: 6 },
    abvPercent: { min: 4.0, max: 5.5 },
  },

  // --- Category 2: International Lager ---
  {
    id: 'international-pale-lager',
    name: 'International Pale Lager',
    category: 'International Lager',
    description: 'Very pale, highly-carbonated, adjunct-leaning mainstream lager.',
    og: { min: 1.042, max: 1.05 },
    fg: { min: 1.008, max: 1.012 },
    ibu: { min: 18, max: 25 },
    srm: { min: 2, max: 6 },
    abvPercent: { min: 4.6, max: 6.0 },
  },
  {
    id: 'international-amber-lager',
    name: 'International Amber Lager',
    category: 'International Lager',
    description: 'Amber, mild-flavored mainstream lager with light caramel notes.',
    og: { min: 1.042, max: 1.05 },
    fg: { min: 1.008, max: 1.012 },
    ibu: { min: 8, max: 25 },
    srm: { min: 8, max: 17 },
    abvPercent: { min: 4.6, max: 6.0 },
  },
  {
    id: 'international-dark-lager',
    name: 'International Dark Lager',
    category: 'International Lager',
    description: 'Dark, mild-flavored mainstream lager with light roast/caramel notes.',
    og: { min: 1.044, max: 1.056 },
    fg: { min: 1.008, max: 1.012 },
    ibu: { min: 8, max: 20 },
    srm: { min: 14, max: 22 },
    abvPercent: { min: 4.2, max: 6.0 },
  },

  // --- Category 3: Czech Lager (remaining) ---
  {
    id: 'czech-pale-lager',
    name: 'Czech Pale Lager',
    category: 'Czech Lager',
    description: 'Low-strength, malty-crisp session lager, a lighter cousin of Czech Pilsner.',
    og: { min: 1.028, max: 1.044 },
    fg: { min: 1.008, max: 1.014 },
    ibu: { min: 20, max: 35 },
    srm: { min: 3, max: 6 },
    abvPercent: { min: 3.0, max: 4.1 },
  },
  {
    id: 'czech-amber-lager',
    name: 'Czech Amber Lager',
    category: 'Czech Lager',
    description: 'Malty amber Czech lager with caramel sweetness and balanced bitterness.',
    og: { min: 1.044, max: 1.05 },
    fg: { min: 1.014, max: 1.02 },
    ibu: { min: 18, max: 30 },
    srm: { min: 10, max: 16 },
    abvPercent: { min: 4.4, max: 5.4 },
  },
  {
    id: 'czech-dark-lager',
    name: 'Czech Dark Lager',
    category: 'Czech Lager',
    description: 'Dark, malty-sweet Czech lager with roasted, bready character.',
    og: { min: 1.044, max: 1.06 },
    fg: { min: 1.014, max: 1.02 },
    ibu: { min: 18, max: 34 },
    srm: { min: 17, max: 35 },
    abvPercent: { min: 3.8, max: 5.8 },
  },

  // --- Category 4: Pale Malty European Lager ---
  {
    id: 'festbier',
    name: 'Festbier',
    category: 'Pale Malty European Lager',
    description: 'Strong, pale-golden, malty-smooth festival lager (modern Oktoberfest beer).',
    og: { min: 1.054, max: 1.057 },
    fg: { min: 1.01, max: 1.014 },
    ibu: { min: 18, max: 25 },
    srm: { min: 4, max: 7 },
    abvPercent: { min: 5.8, max: 6.3 },
  },

  // --- Category 5: Pale Bitter European Beer (remaining) ---
  {
    id: 'german-leichtbier',
    name: 'German Leichtbier',
    category: 'Pale Bitter European Beer',
    description: 'Very low-alcohol, light-bodied German session lager.',
    og: { min: 1.026, max: 1.034 },
    fg: { min: 1.006, max: 1.01 },
    ibu: { min: 15, max: 28 },
    srm: { min: 2, max: 4 },
    abvPercent: { min: 2.4, max: 3.6 },
  },
  {
    id: 'kolsch',
    name: 'Kölsch',
    category: 'Pale Bitter European Beer',
    description: 'Pale, delicate, subtly fruity German ale, lagered for a clean finish.',
    og: { min: 1.044, max: 1.05 },
    fg: { min: 1.007, max: 1.011 },
    ibu: { min: 18, max: 30 },
    srm: { min: 3.5, max: 5 },
    abvPercent: { min: 4.4, max: 5.2 },
  },
  {
    id: 'german-exportbier',
    name: 'German Helles Exportbier',
    category: 'Pale Bitter European Beer',
    description: 'Pale, smooth, moderately strong German lager, malty with clean hop balance.',
    og: { min: 1.048, max: 1.056 },
    fg: { min: 1.01, max: 1.015 },
    ibu: { min: 20, max: 30 },
    srm: { min: 3, max: 6 },
    abvPercent: { min: 4.8, max: 6.0 },
  },

  // --- Category 6: Amber Malty European Lager (remaining) ---
  {
    id: 'rauchbier',
    name: 'Rauchbier',
    category: 'Amber Malty European Lager',
    description: 'Amber Marzen-style lager with pronounced smoky, beechwood-malt character.',
    og: { min: 1.05, max: 1.057 },
    fg: { min: 1.012, max: 1.016 },
    ibu: { min: 20, max: 30 },
    srm: { min: 12, max: 22 },
    abvPercent: { min: 4.8, max: 6.0 },
  },
  {
    id: 'dunkles-bock',
    name: 'Dunkles Bock',
    category: 'Amber Malty European Lager',
    description: 'Strong, malty, toasty dark-amber German lager with restrained bitterness.',
    og: { min: 1.064, max: 1.072 },
    fg: { min: 1.013, max: 1.019 },
    ibu: { min: 20, max: 27 },
    srm: { min: 14, max: 22 },
    abvPercent: { min: 6.3, max: 7.6 },
  },

  // --- Category 7: Amber Bitter European Beer (remaining) ---
  {
    id: 'altbier',
    name: 'Altbier',
    category: 'Amber Bitter European Beer',
    description: 'Copper, clean, moderately bitter German ale, lagered for smoothness.',
    og: { min: 1.046, max: 1.054 },
    fg: { min: 1.008, max: 1.014 },
    ibu: { min: 25, max: 50 },
    srm: { min: 11, max: 17 },
    abvPercent: { min: 4.5, max: 5.2 },
  },

  // --- Category 8: Dark European Lager ---
  {
    id: 'munich-dunkel',
    name: 'Munich Dunkel',
    category: 'Dark European Lager',
    description: 'Malty, bready-chocolatey dark-brown Bavarian lager, smooth and clean.',
    og: { min: 1.048, max: 1.056 },
    fg: { min: 1.01, max: 1.016 },
    ibu: { min: 16, max: 25 },
    srm: { min: 14, max: 28 },
    abvPercent: { min: 4.5, max: 5.6 },
  },
  {
    id: 'schwarzbier',
    name: 'Schwarzbier',
    category: 'Dark European Lager',
    description: 'Black, surprisingly light-bodied German lager with mild roast character.',
    og: { min: 1.046, max: 1.053 },
    fg: { min: 1.01, max: 1.016 },
    ibu: { min: 20, max: 30 },
    srm: { min: 17, max: 30 },
    abvPercent: { min: 4.4, max: 5.4 },
  },

  // --- Category 9: Strong European Beer ---
  {
    id: 'doppelbock',
    name: 'Doppelbock',
    category: 'Strong European Beer',
    description: 'Big, rich, malty-strong dark lager with deep bready/toffee complexity.',
    og: { min: 1.072, max: 1.112 },
    fg: { min: 1.016, max: 1.024 },
    ibu: { min: 16, max: 26 },
    srm: { min: 6, max: 25 },
    abvPercent: { min: 7.0, max: 10.0 },
  },
  {
    id: 'eisbock',
    name: 'Eisbock',
    category: 'Strong European Beer',
    description: 'Intensely rich, warming, freeze-concentrated strong dark German lager.',
    og: { min: 1.078, max: 1.12 },
    fg: { min: 1.02, max: 1.035 },
    ibu: { min: 25, max: 35 },
    srm: { min: 18, max: 30 },
    abvPercent: { min: 9.0, max: 14.0 },
  },
  {
    id: 'baltic-porter',
    name: 'Baltic Porter',
    category: 'Strong European Beer',
    description: 'Strong, smooth, dark lager (or lager-like ale) with rich malt and dried-fruit notes.',
    og: { min: 1.06, max: 1.09 },
    fg: { min: 1.016, max: 1.024 },
    ibu: { min: 20, max: 40 },
    srm: { min: 17, max: 30 },
    abvPercent: { min: 6.5, max: 9.5 },
  },

  // --- Category 10: German Wheat Beer (remaining) ---
  {
    id: 'dunkles-weissbier',
    name: 'Dunkles Weizen',
    category: 'German Wheat Beer',
    description: 'Dark wheat ale combining banana/clove yeast character with roasted malt.',
    og: { min: 1.044, max: 1.056 },
    fg: { min: 1.01, max: 1.014 },
    ibu: { min: 10, max: 18 },
    srm: { min: 14, max: 23 },
    abvPercent: { min: 4.3, max: 5.6 },
  },
  {
    id: 'weizenbock',
    name: 'Weizenbock',
    category: 'German Wheat Beer',
    description: 'Strong, dark or pale wheat bock with rich fruity ester and banana/clove notes.',
    og: { min: 1.064, max: 1.09 },
    fg: { min: 1.015, max: 1.022 },
    ibu: { min: 15, max: 30 },
    srm: { min: 6, max: 25 },
    abvPercent: { min: 6.5, max: 9.0 },
  },

  // --- Category 11: British Bitter (remaining) ---
  {
    id: 'best-bitter',
    name: 'Best Bitter',
    category: 'British Bitter',
    description: 'Moderate-strength, malt-balanced English session ale with earthy hops.',
    og: { min: 1.04, max: 1.048 },
    fg: { min: 1.008, max: 1.012 },
    ibu: { min: 25, max: 40 },
    srm: { min: 8, max: 16 },
    abvPercent: { min: 3.8, max: 4.6 },
  },

  // --- Category 12: Pale Commonwealth Beer ---
  {
    id: 'british-golden-ale',
    name: 'British Golden Ale',
    category: 'Pale Commonwealth Beer',
    description: 'Pale, refreshing, easy-drinking modern English session ale.',
    og: { min: 1.038, max: 1.05 },
    fg: { min: 1.006, max: 1.012 },
    ibu: { min: 20, max: 45 },
    srm: { min: 2, max: 6 },
    abvPercent: { min: 3.8, max: 5.0 },
  },
  {
    id: 'australian-sparkling-ale',
    name: 'Australian Sparkling Ale',
    category: 'Pale Commonwealth Beer',
    description: 'Highly-carbonated, fruity-yet-clean pale Australian ale.',
    og: { min: 1.038, max: 1.05 },
    fg: { min: 1.004, max: 1.011 },
    ibu: { min: 20, max: 32 },
    srm: { min: 4, max: 8 },
    abvPercent: { min: 4.5, max: 6.2 },
  },
  {
    id: 'english-ipa',
    name: 'English IPA',
    category: 'Pale Commonwealth Beer',
    description: 'Malty-balanced, earthy-hopped English interpretation of the historical IPA.',
    og: { min: 1.05, max: 1.075 },
    fg: { min: 1.01, max: 1.018 },
    ibu: { min: 40, max: 60 },
    srm: { min: 6, max: 14 },
    abvPercent: { min: 5.0, max: 7.5 },
  },

  // --- Category 13: Brown British Beer ---
  {
    id: 'dark-mild',
    name: 'Dark Mild',
    category: 'Brown British Beer',
    description: 'Low-strength, malty-sweet dark English session ale, gently roasty.',
    og: { min: 1.03, max: 1.038 },
    fg: { min: 1.008, max: 1.013 },
    ibu: { min: 10, max: 25 },
    srm: { min: 12, max: 25 },
    abvPercent: { min: 3.0, max: 3.8 },
  },
  {
    id: 'british-brown-ale',
    name: 'British Brown Ale',
    category: 'Brown British Beer',
    description: 'Malty, nutty, low-bitterness brown English ale with light caramel notes.',
    og: { min: 1.04, max: 1.052 },
    fg: { min: 1.008, max: 1.013 },
    ibu: { min: 20, max: 30 },
    srm: { min: 12, max: 22 },
    abvPercent: { min: 4.2, max: 5.4 },
  },
  {
    id: 'english-porter',
    name: 'English Porter',
    category: 'Brown British Beer',
    description: 'Balanced, moderately roasty dark English ale, drier than a stout.',
    og: { min: 1.04, max: 1.052 },
    fg: { min: 1.008, max: 1.014 },
    ibu: { min: 18, max: 35 },
    srm: { min: 20, max: 30 },
    abvPercent: { min: 4.0, max: 5.4 },
  },

  // --- Category 14: Scottish Ale ---
  {
    id: 'scottish-light',
    name: 'Scottish Light (60/-)',
    category: 'Scottish Ale',
    description: 'Low-strength, malty, lightly-smoky Scottish session ale.',
    og: { min: 1.03, max: 1.035 },
    fg: { min: 1.01, max: 1.013 },
    ibu: { min: 10, max: 20 },
    srm: { min: 9, max: 17 },
    abvPercent: { min: 2.5, max: 3.2 },
  },
  {
    id: 'scottish-heavy',
    name: 'Scottish Heavy (70/-)',
    category: 'Scottish Ale',
    description: 'Malt-forward Scottish ale with restrained bitterness and gentle smoke.',
    og: { min: 1.035, max: 1.04 },
    fg: { min: 1.01, max: 1.015 },
    ibu: { min: 10, max: 25 },
    srm: { min: 9, max: 17 },
    abvPercent: { min: 3.2, max: 3.9 },
  },
  {
    id: 'scottish-export',
    name: 'Scottish Export (80/-)',
    category: 'Scottish Ale',
    description: 'Richer, maltier Scottish ale, deep caramel notes and low hop character.',
    og: { min: 1.04, max: 1.06 },
    fg: { min: 1.01, max: 1.017 },
    ibu: { min: 15, max: 30 },
    srm: { min: 9, max: 17 },
    abvPercent: { min: 3.9, max: 5.0 },
  },

  // --- Category 15: Irish Beer (remaining) ---
  {
    id: 'irish-red-ale',
    name: 'Irish Red Ale',
    category: 'Irish Beer',
    description: 'Smooth, malty-sweet, low-bitterness reddish-amber Irish session ale.',
    og: { min: 1.036, max: 1.046 },
    fg: { min: 1.01, max: 1.014 },
    ibu: { min: 18, max: 28 },
    srm: { min: 9, max: 18 },
    abvPercent: { min: 3.8, max: 5.0 },
  },
  {
    id: 'irish-extra-stout',
    name: 'Irish Extra Stout',
    category: 'Irish Beer',
    description: 'Fuller-bodied, roastier, stronger take on dry Irish stout.',
    og: { min: 1.052, max: 1.062 },
    fg: { min: 1.01, max: 1.014 },
    ibu: { min: 35, max: 50 },
    srm: { min: 25, max: 40 },
    abvPercent: { min: 5.5, max: 6.5 },
  },

  // --- Category 16: Dark British Beer (remaining) ---
  {
    id: 'oatmeal-stout',
    name: 'Oatmeal Stout',
    category: 'Dark British Beer',
    description: 'Silky-smooth, roasty stout with a rounded, creamy oat-driven mouthfeel.',
    og: { min: 1.042, max: 1.06 },
    fg: { min: 1.01, max: 1.018 },
    ibu: { min: 25, max: 40 },
    srm: { min: 22, max: 40 },
    abvPercent: { min: 4.2, max: 5.9 },
  },
  {
    id: 'tropical-stout',
    name: 'Tropical Stout',
    category: 'Dark British Beer',
    description: 'Sweet, fruity-roasty, moderately strong stout brewed for warm climates.',
    og: { min: 1.056, max: 1.075 },
    fg: { min: 1.01, max: 1.018 },
    ibu: { min: 30, max: 50 },
    srm: { min: 20, max: 35 },
    abvPercent: { min: 5.5, max: 8.0 },
  },
  {
    id: 'foreign-extra-stout',
    name: 'Foreign Extra Stout',
    category: 'Dark British Beer',
    description: 'Strong, robust, roast-forward export stout with warming alcohol.',
    og: { min: 1.056, max: 1.075 },
    fg: { min: 1.01, max: 1.018 },
    ibu: { min: 30, max: 70 },
    srm: { min: 30, max: 40 },
    abvPercent: { min: 6.3, max: 8.0 },
  },

  // --- Category 17: Strong British Ale (remaining) ---
  {
    id: 'british-strong-ale',
    name: 'British Strong Ale',
    category: 'Strong British Ale',
    description: 'Malty, fruity, moderately strong English ale, broad and varied in character.',
    og: { min: 1.055, max: 1.08 },
    fg: { min: 1.015, max: 1.022 },
    ibu: { min: 30, max: 60 },
    srm: { min: 8, max: 22 },
    abvPercent: { min: 6.0, max: 9.0 },
  },
  {
    id: 'old-ale',
    name: 'Old Ale',
    category: 'Strong British Ale',
    description: 'Dark, rich, oxidative-leaning strong English ale, often aged.',
    og: { min: 1.06, max: 1.09 },
    fg: { min: 1.015, max: 1.022 },
    ibu: { min: 30, max: 60 },
    srm: { min: 10, max: 22 },
    abvPercent: { min: 6.0, max: 9.0 },
  },
  {
    id: 'wee-heavy',
    name: 'Wee Heavy',
    category: 'Strong British Ale',
    description: 'Rich, malty-sweet, strong Scottish ale with deep caramel and light smoke.',
    og: { min: 1.07, max: 1.13 },
    fg: { min: 1.018, max: 1.028 },
    ibu: { min: 17, max: 35 },
    srm: { min: 14, max: 25 },
    abvPercent: { min: 6.5, max: 10.0 },
  },

  // --- Category 18: Pale American Ale ---
  {
    id: 'blonde-ale',
    name: 'Blonde Ale',
    category: 'Pale American Ale',
    description: 'Easy-drinking, clean, lightly-hopped pale American ale.',
    og: { min: 1.038, max: 1.054 },
    fg: { min: 1.008, max: 1.013 },
    ibu: { min: 15, max: 28 },
    srm: { min: 3, max: 6 },
    abvPercent: { min: 3.8, max: 5.5 },
  },

  // --- Category 19: Amber and Brown American Beer (remaining) ---
  {
    id: 'california-common',
    name: 'California Common (Steam Beer)',
    category: 'Amber and Brown American Beer',
    description: 'Amber, lager-yeast-at-ale-temps hybrid with toasty malt and earthy hops.',
    og: { min: 1.048, max: 1.054 },
    fg: { min: 1.011, max: 1.014 },
    ibu: { min: 30, max: 45 },
    srm: { min: 8, max: 17 },
    abvPercent: { min: 4.5, max: 5.5 },
  },

  // --- Category 20: American Porter and Stout (remaining) ---
  {
    id: 'american-stout',
    name: 'American Stout',
    category: 'American Porter and Stout',
    description: 'Roasty, hoppier, more assertive American take on stout.',
    og: { min: 1.05, max: 1.075 },
    fg: { min: 1.01, max: 1.022 },
    ibu: { min: 35, max: 75 },
    srm: { min: 30, max: 40 },
    abvPercent: { min: 5.0, max: 7.0 },
  },

  // --- Category 21: IPA (remaining specialty variants) ---
  {
    id: 'belgian-ipa',
    name: 'Belgian IPA',
    category: 'IPA',
    description: 'Hoppy American-style IPA fermented with a fruity/spicy Belgian yeast strain.',
    og: { min: 1.05, max: 1.07 },
    fg: { min: 1.008, max: 1.016 },
    ibu: { min: 50, max: 100 },
    srm: { min: 6, max: 15 },
    abvPercent: { min: 6.2, max: 9.5 },
  },
  {
    id: 'black-ipa',
    name: 'Black IPA',
    category: 'IPA',
    description: 'Dark-roasted IPA with hop-forward aroma/bitterness despite its color.',
    og: { min: 1.05, max: 1.085 },
    fg: { min: 1.01, max: 1.018 },
    ibu: { min: 50, max: 90 },
    srm: { min: 25, max: 40 },
    abvPercent: { min: 5.5, max: 9.0 },
  },
  {
    id: 'rye-ipa',
    name: 'Rye IPA',
    category: 'IPA',
    description: 'Hoppy American IPA with a spicy, dry rye-malt backbone.',
    og: { min: 1.056, max: 1.07 },
    fg: { min: 1.008, max: 1.014 },
    ibu: { min: 40, max: 70 },
    srm: { min: 6, max: 14 },
    abvPercent: { min: 5.5, max: 7.5 },
  },
  {
    id: 'white-ipa',
    name: 'White IPA',
    category: 'IPA',
    description: 'Hoppy IPA crossed with a witbier base -- wheat, citrus, spice, and hop aroma.',
    og: { min: 1.05, max: 1.07 },
    fg: { min: 1.008, max: 1.016 },
    ibu: { min: 40, max: 70 },
    srm: { min: 4, max: 7 },
    abvPercent: { min: 5.5, max: 7.0 },
  },

  // --- Category 22: Strong Belgian Ale (Blonde Strong) ---
  {
    id: 'belgian-golden-strong',
    name: 'Belgian Golden Strong Ale',
    category: 'Strong Belgian Ale',
    description: 'Deceptively light-drinking, high-alcohol pale Belgian ale, dry and effervescent.',
    og: { min: 1.07, max: 1.095 },
    fg: { min: 1.005, max: 1.016 },
    ibu: { min: 22, max: 35 },
    srm: { min: 3, max: 6 },
    abvPercent: { min: 7.5, max: 10.5 },
  },
  {
    id: 'belgian-dark-strong',
    name: 'Belgian Dark Strong Ale',
    category: 'Strong Belgian Ale',
    description: 'Rich, complex, high-alcohol dark Belgian ale with dried-fruit character.',
    og: { min: 1.075, max: 1.11 },
    fg: { min: 1.01, max: 1.024 },
    ibu: { min: 20, max: 35 },
    srm: { min: 12, max: 22 },
    abvPercent: { min: 8.0, max: 12.0 },
  },

  // --- Category 24: Belgian Ale (remaining) ---
  {
    id: 'belgian-blond-ale',
    name: 'Belgian Blond Ale',
    category: 'Belgian Ale',
    description: 'Easy-drinking, subtly spicy, golden Belgian ale, softer than Tripel.',
    og: { min: 1.062, max: 1.075 },
    fg: { min: 1.008, max: 1.018 },
    ibu: { min: 15, max: 30 },
    srm: { min: 4, max: 7 },
    abvPercent: { min: 6.0, max: 7.5 },
  },
  {
    id: 'belgian-pale-ale',
    name: 'Belgian Pale Ale',
    category: 'Belgian Ale',
    description: 'Malty, gently spicy, easy-drinking session-strength Belgian ale.',
    og: { min: 1.048, max: 1.054 },
    fg: { min: 1.01, max: 1.014 },
    ibu: { min: 20, max: 30 },
    srm: { min: 8, max: 14 },
    abvPercent: { min: 4.8, max: 5.5 },
  },
  {
    id: 'biere-de-garde',
    name: 'Bière de Garde',
    category: 'Belgian Ale',
    description: 'Malty, toasty, moderately strong French farmhouse ale, smooth and rich.',
    og: { min: 1.06, max: 1.08 },
    fg: { min: 1.01, max: 1.016 },
    ibu: { min: 18, max: 28 },
    srm: { min: 6, max: 19 },
    abvPercent: { min: 6.0, max: 8.5 },
  },

  // --- Category 23: European Sour Ale (remaining) ---
  {
    id: 'flanders-red',
    name: 'Flanders Red Ale',
    category: 'European Sour Ale',
    description: 'Complex, vinous, sour-sweet red ale with wine-like acidity.',
    og: { min: 1.048, max: 1.057 },
    fg: { min: 1.002, max: 1.012 },
    ibu: { min: 10, max: 25 },
    srm: { min: 10, max: 16 },
    abvPercent: { min: 4.6, max: 6.5 },
  },
  {
    id: 'oud-bruin',
    name: 'Oud Bruin',
    category: 'European Sour Ale',
    description: 'Malty-sweet-sour dark Belgian ale with rich, rounded acidity.',
    og: { min: 1.04, max: 1.074 },
    fg: { min: 1.008, max: 1.012 },
    ibu: { min: 20, max: 25 },
    srm: { min: 15, max: 22 },
    abvPercent: { min: 4.0, max: 8.0 },
  },
  {
    id: 'gueuze',
    name: 'Gueuze',
    category: 'European Sour Ale',
    description: 'Blended, bottle-conditioned, funky-tart spontaneously-fermented Belgian ale.',
    og: { min: 1.04, max: 1.06 },
    fg: { min: 1.0, max: 1.006 },
    ibu: { min: 0, max: 10 },
    srm: { min: 6, max: 13 },
    abvPercent: { min: 5.0, max: 8.0 },
  },

  // --- Category 26: Trappist Ale (remaining) ---
  {
    id: 'trappist-single',
    name: 'Trappist Single',
    category: 'Trappist Ale',
    description: 'Pale, delicate, low-strength monastic table ale, dry and quenching.',
    og: { min: 1.044, max: 1.054 },
    fg: { min: 1.004, max: 1.01 },
    ibu: { min: 25, max: 45 },
    srm: { min: 3, max: 5 },
    abvPercent: { min: 4.8, max: 6.0 },
  },
  {
    id: 'trappist-quadrupel',
    name: 'Trappist Quadrupel',
    category: 'Trappist Ale',
    description: 'Very strong, rich, dark, dried-fruit-and-spice-driven monastic ale.',
    og: { min: 1.078, max: 1.115 },
    fg: { min: 1.008, max: 1.024 },
    ibu: { min: 20, max: 45 },
    srm: { min: 12, max: 22 },
    abvPercent: { min: 8.5, max: 12.0 },
  },
];
