/**
 * BJCP-style numeric target ranges for common beer styles.
 *
 * These are the vital-statistic ranges (OG, FG, IBU, SRM color, ABV) --
 * factual numeric reference data of the kind published across the
 * brewing community (BJCP guidelines, brewing software, homebrew club
 * references) for these well-known style categories. The style names
 * and numeric ranges reflect commonly published figures; the
 * descriptions below are original one-line summaries written for this
 * app, not copied from the BJCP guidelines document's descriptive text.
 * For full style guidance (history, appearance, flavor, commercial
 * examples), always consult the official BJCP Style Guidelines
 * (bjcp.org) -- this is a quick numeric reference only, covering a
 * representative subset of styles, not the complete BJCP category list.
 */

export interface RangeMinMax {
  min: number;
  max: number;
}

export interface BjcpStyleRange {
  id: string;
  name: string;
  category: string;
  description: string;
  og: RangeMinMax;
  fg: RangeMinMax;
  ibu: RangeMinMax;
  srm: RangeMinMax;
  abvPercent: RangeMinMax;
}

export const BJCP_STYLES: BjcpStyleRange[] = [
  {
    id: 'american-light-lager',
    name: 'American Light Lager',
    category: 'Standard American Beer',
    description: 'Very pale, light-bodied, highly attenuated, minimal hop character.',
    og: { min: 1.028, max: 1.04 },
    fg: { min: 0.998, max: 1.008 },
    ibu: { min: 8, max: 12 },
    srm: { min: 2, max: 3 },
    abvPercent: { min: 2.8, max: 4.2 },
  },
  {
    id: 'american-lager',
    name: 'American Lager',
    category: 'Standard American Beer',
    description: 'Pale, crisp, well-attenuated lager with subtle hop bitterness.',
    og: { min: 1.04, max: 1.05 },
    fg: { min: 1.004, max: 1.01 },
    ibu: { min: 8, max: 18 },
    srm: { min: 2, max: 4 },
    abvPercent: { min: 4.2, max: 5.3 },
  },
  {
    id: 'czech-pilsner',
    name: 'Czech Premium Pale Lager (Pilsner)',
    category: 'Czech Lager',
    description: 'Golden, malty-yet-crisp lager with pronounced Saaz hop character.',
    og: { min: 1.044, max: 1.06 },
    fg: { min: 1.013, max: 1.017 },
    ibu: { min: 30, max: 45 },
    srm: { min: 3.5, max: 6 },
    abvPercent: { min: 4.2, max: 5.8 },
  },
  {
    id: 'german-pilsner',
    name: 'German Pils',
    category: 'Pale Bitter European Beer',
    description: 'Pale, dry, highly-attenuated lager with firm, clean hop bitterness.',
    og: { min: 1.044, max: 1.05 },
    fg: { min: 1.008, max: 1.013 },
    ibu: { min: 22, max: 40 },
    srm: { min: 2, max: 5 },
    abvPercent: { min: 4.4, max: 5.2 },
  },
  {
    id: 'munich-helles',
    name: 'Munich Helles',
    category: 'Amber Malty European Beer',
    description: 'Soft, malty-sweet golden lager with restrained noble hop bitterness.',
    og: { min: 1.045, max: 1.051 },
    fg: { min: 1.008, max: 1.012 },
    ibu: { min: 16, max: 22 },
    srm: { min: 3, max: 5 },
    abvPercent: { min: 4.7, max: 5.4 },
  },
  {
    id: 'vienna-lager',
    name: 'Vienna Lager',
    category: 'Amber Malty European Beer',
    description: 'Toasty amber lager with moderate malt sweetness and clean hop balance.',
    og: { min: 1.045, max: 1.055 },
    fg: { min: 1.01, max: 1.014 },
    ibu: { min: 18, max: 30 },
    srm: { min: 9, max: 15 },
    abvPercent: { min: 4.5, max: 5.5 },
  },
  {
    id: 'oktoberfest-marzen',
    name: 'Oktoberfestbier / Marzen',
    category: 'Amber Malty European Beer',
    description: 'Rich, toasty amber-to-copper lager, malt-forward with clean finish.',
    og: { min: 1.054, max: 1.057 },
    fg: { min: 1.01, max: 1.014 },
    ibu: { min: 18, max: 24 },
    srm: { min: 8, max: 17 },
    abvPercent: { min: 5.8, max: 6.3 },
  },
  {
    id: 'american-pale-ale',
    name: 'American Pale Ale',
    category: 'Pale American Ale',
    description: 'Balanced, moderately hoppy pale ale with citrusy/piney American hop character.',
    og: { min: 1.045, max: 1.06 },
    fg: { min: 1.01, max: 1.015 },
    ibu: { min: 30, max: 50 },
    srm: { min: 5, max: 10 },
    abvPercent: { min: 4.5, max: 6.2 },
  },
  {
    id: 'english-bitter',
    name: 'Ordinary Bitter',
    category: 'British Bitter',
    description: 'Low-strength, malt-balanced English session ale with earthy hop character.',
    og: { min: 1.03, max: 1.039 },
    fg: { min: 1.007, max: 1.011 },
    ibu: { min: 25, max: 35 },
    srm: { min: 8, max: 14 },
    abvPercent: { min: 3.2, max: 3.8 },
  },
  {
    id: 'esb',
    name: 'Strong Bitter (ESB)',
    category: 'British Bitter',
    description: 'Robust, malt-forward English ale with balanced earthy hop bitterness.',
    og: { min: 1.048, max: 1.06 },
    fg: { min: 1.01, max: 1.016 },
    ibu: { min: 30, max: 50 },
    srm: { min: 8, max: 18 },
    abvPercent: { min: 4.6, max: 6.2 },
  },
  {
    id: 'american-amber-ale',
    name: 'American Amber Ale',
    category: 'Amber and Brown American Beer',
    description: 'Caramel-malty amber ale with moderate American hop bitterness/aroma.',
    og: { min: 1.045, max: 1.06 },
    fg: { min: 1.01, max: 1.015 },
    ibu: { min: 25, max: 40 },
    srm: { min: 10, max: 17 },
    abvPercent: { min: 4.5, max: 6.2 },
  },
  {
    id: 'brown-ale',
    name: 'American Brown Ale',
    category: 'Amber and Brown American Beer',
    description: 'Malty brown ale with roast/chocolate notes and moderate hop bitterness.',
    og: { min: 1.045, max: 1.06 },
    fg: { min: 1.01, max: 1.016 },
    ibu: { min: 20, max: 40 },
    srm: { min: 18, max: 35 },
    abvPercent: { min: 4.3, max: 6.2 },
  },
  {
    id: 'porter',
    name: 'American Porter',
    category: 'Brown British Beer / American Porter',
    description: 'Dark, roasty ale with chocolate/coffee notes, moderate bitterness.',
    og: { min: 1.05, max: 1.07 },
    fg: { min: 1.012, max: 1.018 },
    ibu: { min: 20, max: 40 },
    srm: { min: 22, max: 35 },
    abvPercent: { min: 4.8, max: 6.5 },
  },
  {
    id: 'dry-irish-stout',
    name: 'Irish Stout',
    category: 'Strong British Ale / Stout',
    description: 'Dry, roasty, coffee-like dark ale with restrained sweetness.',
    og: { min: 1.036, max: 1.044 },
    fg: { min: 1.007, max: 1.011 },
    ibu: { min: 25, max: 45 },
    srm: { min: 25, max: 40 },
    abvPercent: { min: 4.0, max: 4.5 },
  },
  {
    id: 'sweet-stout',
    name: 'Sweet Stout',
    category: 'Strong British Ale / Stout',
    description: 'Dark, full-bodied, sweet stout with roasty malt and low bitterness.',
    og: { min: 1.044, max: 1.06 },
    fg: { min: 1.012, max: 1.024 },
    ibu: { min: 20, max: 40 },
    srm: { min: 30, max: 40 },
    abvPercent: { min: 4.0, max: 6.0 },
  },
  {
    id: 'imperial-stout',
    name: 'Imperial Stout',
    category: 'Strong British Ale / Stout',
    description: 'Big, rich, roasty dark ale with high alcohol warmth and complex malt.',
    og: { min: 1.075, max: 1.115 },
    fg: { min: 1.018, max: 1.03 },
    ibu: { min: 50, max: 90 },
    srm: { min: 30, max: 40 },
    abvPercent: { min: 8.0, max: 12.0 },
  },
  {
    id: 'american-ipa',
    name: 'American IPA',
    category: 'IPA',
    description: 'Assertively hoppy, moderately strong pale ale with citrus/pine/resin hop character.',
    og: { min: 1.056, max: 1.07 },
    fg: { min: 1.008, max: 1.014 },
    ibu: { min: 40, max: 70 },
    srm: { min: 6, max: 14 },
    abvPercent: { min: 5.5, max: 7.5 },
  },
  {
    id: 'hazy-ipa',
    name: 'Hazy IPA (NEIPA)',
    category: 'IPA',
    description: 'Soft, juicy, hazy IPA with intense fruit-forward hop aroma and low bitterness.',
    og: { min: 1.06, max: 1.085 },
    fg: { min: 1.01, max: 1.015 },
    ibu: { min: 25, max: 60 },
    srm: { min: 3, max: 7 },
    abvPercent: { min: 6.0, max: 9.0 },
  },
  {
    id: 'double-ipa',
    name: 'Double/Imperial IPA',
    category: 'IPA',
    description: 'Big, intensely hoppy IPA with high alcohol strength and firm bitterness.',
    og: { min: 1.065, max: 1.085 },
    fg: { min: 1.008, max: 1.018 },
    ibu: { min: 60, max: 120 },
    srm: { min: 6, max: 14 },
    abvPercent: { min: 7.5, max: 10.0 },
  },
  {
    id: 'weissbier',
    name: 'German Weissbier (Hefeweizen)',
    category: 'German Wheat Beer',
    description: 'Pale, wheat-forward ale with banana/clove yeast character, low bitterness.',
    og: { min: 1.044, max: 1.053 },
    fg: { min: 1.008, max: 1.014 },
    ibu: { min: 8, max: 15 },
    srm: { min: 2, max: 6 },
    abvPercent: { min: 4.3, max: 5.6 },
  },
  {
    id: 'witbier',
    name: 'Witbier',
    category: 'Belgian Wheat Beer',
    description: 'Pale, tangy, spiced (coriander/orange peel) Belgian wheat ale.',
    og: { min: 1.044, max: 1.052 },
    fg: { min: 1.008, max: 1.012 },
    ibu: { min: 8, max: 20 },
    srm: { min: 2, max: 4 },
    abvPercent: { min: 4.5, max: 5.5 },
  },
  {
    id: 'belgian-dubbel',
    name: 'Belgian Dubbel',
    category: 'Trappist Ale',
    description: 'Malty, dark amber Belgian ale with fruity ester and spicy phenol character.',
    og: { min: 1.062, max: 1.075 },
    fg: { min: 1.008, max: 1.018 },
    ibu: { min: 15, max: 25 },
    srm: { min: 10, max: 17 },
    abvPercent: { min: 6.0, max: 7.6 },
  },
  {
    id: 'belgian-tripel',
    name: 'Belgian Tripel',
    category: 'Trappist Ale',
    description: 'Pale, strong Belgian ale, deceptively drinkable with fruity, spicy complexity.',
    og: { min: 1.075, max: 1.085 },
    fg: { min: 1.008, max: 1.014 },
    ibu: { min: 20, max: 40 },
    srm: { min: 4.5, max: 7 },
    abvPercent: { min: 7.5, max: 9.5 },
  },
  {
    id: 'saison',
    name: 'Saison',
    category: 'Belgian/French Ale',
    description: 'Dry, highly-attenuated, peppery/fruity farmhouse ale with earthy hop notes.',
    og: { min: 1.048, max: 1.065 },
    fg: { min: 1.002, max: 1.012 },
    ibu: { min: 20, max: 35 },
    srm: { min: 5, max: 14 },
    abvPercent: { min: 5.0, max: 7.0 },
  },
  {
    id: 'berliner-weisse',
    name: 'Berliner Weisse',
    category: 'Sour Ale',
    description: 'Very pale, tart, low-alcohol wheat sour ale, refreshing and lightly fruity.',
    og: { min: 1.028, max: 1.032 },
    fg: { min: 1.003, max: 1.006 },
    ibu: { min: 3, max: 8 },
    srm: { min: 2, max: 3 },
    abvPercent: { min: 2.8, max: 3.8 },
  },
  {
    id: 'barleywine',
    name: 'English Barleywine',
    category: 'Strong Ale',
    description: 'Big, rich, malty-sweet strong ale with warming alcohol and complex fruit/toffee notes.',
    og: { min: 1.09, max: 1.12 },
    fg: { min: 1.018, max: 1.03 },
    ibu: { min: 35, max: 70 },
    srm: { min: 8, max: 22 },
    abvPercent: { min: 8.0, max: 12.0 },
  },
];
