/**
 * Priming sugar / carbonation calculator.
 *
 * Standard published relationship (the same one taught generally in
 * brewing science): the CO2 already dissolved in beer at fermentation
 * temperature ("residual CO2") is subtracted from the desired final CO2
 * volumes to get the CO2 that must be generated by priming sugar. That
 * CO2 requirement (g/L) is converted to a sugar mass using each sugar's
 * fermentable CO2 yield.
 *
 * Residual CO2 (volumes) as a function of temperature is estimated with
 * the standard published approximation:
 *   residualCO2 = 3.0378 - 0.050062*T + 0.00026555*T^2   (T in °C)
 * This is a widely-cited empirical fit to CO2 solubility in beer at
 * atmospheric pressure across normal fermentation/conditioning
 * temperatures.
 */

function safeNonNegative(value: number, fallback = 0): number {
  return Number.isFinite(value) && value >= 0 ? value : fallback;
}

/**
 * Residual (already-dissolved) CO2, in volumes, for beer at the given
 * temperature (°C) at atmospheric pressure -- i.e. the CO2 still in
 * solution from fermentation before any priming/forced carbonation.
 */
export function estimateResidualCo2Volumes(temperatureC: number): number {
  const t = Number.isFinite(temperatureC) ? temperatureC : 20;
  const volumes = 3.0378 - 0.050062 * t + 0.00026555 * t ** 2;
  return Math.max(0, volumes);
}

export interface PrimingSugarType {
  id: string;
  name: string;
  /** CO2 yield, grams of CO2 produced per gram of this sugar when fully fermented. */
  co2YieldGPerG: number;
}

export const PRIMING_SUGARS: PrimingSugarType[] = [
  // Standard published fermentation stoichiometry: sucrose/dextrose
  // ferment to ~0.5 g CO2 per g of pure fermentable sugar; corn sugar
  // (dextrose monohydrate) and DME are slightly lower due to water
  // content / non-fermentable fraction.
  { id: 'dextrose', name: 'Dextrose (Corn Sugar)', co2YieldGPerG: 0.45 },
  { id: 'sucrose', name: 'Table Sugar (Sucrose)', co2YieldGPerG: 0.5 },
  { id: 'dme', name: 'Dried Malt Extract (DME)', co2YieldGPerG: 0.4 },
];

export interface PrimingResult {
  /** CO2 already dissolved at the given conditioning temperature, volumes. */
  residualCo2Volumes: number;
  /** Additional CO2 volumes that priming sugar must generate. */
  co2VolumesToGenerate: number;
  /** Grams of priming sugar needed for the whole batch. */
  primingSugarGrams: number;
  /** True if the beer is already at/above target carbonation (no priming needed). */
  alreadyAtTarget: boolean;
}

/**
 * CO2 volumes convert to mass via the standard relationship: 1 volume
 * of CO2 per liter of beer = 1.96 g/L of dissolved CO2 (CO2 density at
 * STP-equivalent solubility convention used throughout brewing
 * carbonation literature).
 */
const CO2_G_PER_L_PER_VOLUME = 1.96;

/**
 * Compute the priming sugar dose needed to reach `targetCo2Volumes` for
 * a batch of `batchVolumeL`, given the beer's current conditioning
 * temperature (used to estimate residual CO2 already in solution).
 */
export function calculatePrimingDose(
  targetCo2Volumes: number,
  temperatureC: number,
  batchVolumeL: number,
  sugar: PrimingSugarType,
): PrimingResult {
  const safeTarget = safeNonNegative(targetCo2Volumes, 2.4);
  const safeVolume = safeNonNegative(batchVolumeL);
  const residualCo2Volumes = estimateResidualCo2Volumes(temperatureC);

  const co2VolumesToGenerate = Math.max(0, safeTarget - residualCo2Volumes);

  if (co2VolumesToGenerate <= 0 || safeVolume <= 0 || sugar.co2YieldGPerG <= 0) {
    return {
      residualCo2Volumes,
      co2VolumesToGenerate: 0,
      primingSugarGrams: 0,
      alreadyAtTarget: co2VolumesToGenerate <= 0,
    };
  }

  const co2GramsNeededTotal = co2VolumesToGenerate * CO2_G_PER_L_PER_VOLUME * safeVolume;
  const primingSugarGrams = co2GramsNeededTotal / sugar.co2YieldGPerG;

  return {
    residualCo2Volumes,
    co2VolumesToGenerate,
    primingSugarGrams,
    alreadyAtTarget: false,
  };
}
