import type { Metadata } from 'next';
import { RouteNav } from '@/components/ui/RouteNav';
import { SectionCard } from '@/components/ui/SectionCard';
import { StatHero } from '@/components/ui/StatHero';
import { StatTile } from '@/components/ui/StatTile';
import { HBarChart, type BarDatum } from '@/components/analytics/HBarChart';
import { StyleRangeChart, type StyleRow } from '@/components/analytics/StyleRangeChart';

import indexData from '../../../public/analytics/index.json';
import stylesData from '../../../public/analytics/styles.json';
import hopsData from '../../../public/analytics/hops.json';
import fermentablesData from '../../../public/analytics/fermentables.json';
import yeastsData from '../../../public/analytics/yeasts.json';

export const metadata: Metadata = {
  title: "Recipe Analytics - Indian Brewer's Calculator",
  description:
    'Aggregate insights from real brewing recipes: typical ABV, IBU, and colour by BJCP style, plus the most-used hops, fermentables, and yeasts.',
};

// ---- data shaping (build-time; JSON is generated by scripts/build-analytics.ts)
interface Dist {
  p10: number | null;
  p50: number | null;
  p90: number | null;
}
interface StyleStat {
  style: string;
  count: number;
  og: Dist;
  abv: Dist;
  ibu: Dist;
  srm: Dist;
}
interface Ranked {
  name: string;
  count: number;
}

const styles = stylesData as StyleStat[];
const classified = styles.filter((s) => s.style !== 'Unclassified');

const titleCase = (s: string): string =>
  s.replace(/\b[a-z]/g, (c) => c.toUpperCase());

const toBars = (rows: Ranked[], limit: number): BarDatum[] =>
  rows.slice(0, limit).map((r) => ({ label: titleCase(r.name), value: r.count }));

const styleRows = (metric: 'abv' | 'ibu', limit: number): StyleRow[] =>
  classified.slice(0, limit).map((s) => ({
    style: s.style,
    count: s.count,
    srmP50: s.srm.p50,
    p10: s[metric].p10,
    p50: s[metric].p50,
    p90: s[metric].p90,
  }));

export default function AnalyticsPage() {
  const hops = hopsData as { top: Ranked[]; pairings: Ranked[] };
  const ferments = fermentablesData as { top: Ranked[] };
  const yeasts = yeastsData as { top: Ranked[] };
  const meta = indexData as {
    recipeCount: number;
    ingredientRecipeCount: number;
    styleCount: number;
  };
  const fmt = (n: number) => n.toLocaleString('en-IN');

  return (
    <main className="mx-auto max-w-3xl px-4 py-8 sm:py-10">
      <RouteNav current="analytics" />
      {/* header */}
      <div className="mb-6">
        <h1 className="font-display text-3xl font-extrabold tracking-tight text-amber-900 sm:text-4xl">
          Recipe Analytics
        </h1>
        <p className="mt-1 max-w-prose font-body text-sm text-ink/70">
          What real recipes reveal about typical brewing practice: vital-stat ranges by BJCP style,
          and the ingredients brewers actually reach for. Every number here is <em>computed</em> from
          the recipes, using the same IBU, colour, and style engines that power this calculator.
        </p>
      </div>

      {/* dataset vitals */}
      <StatHero title="The dataset" accentColor="#e08b2d">
        <div className="grid grid-cols-3 gap-2">
          <StatTile label="Recipes" value={fmt(meta.recipeCount)} hint="for style stats" />
          <StatTile label="BJCP styles" value={String(classified.length)} hint="classified" />
          <StatTile label="With ingredients" value={fmt(meta.ingredientRecipeCount)} hint="hop/malt stats" />
        </div>
      </StatHero>

      <div className="mt-6 space-y-6">
        {/* narrative trends */}
        <SectionCard title="What brewers are making now">
          <p className="mb-3 text-xs text-ink/60">A read on recent community output (2025-26).</p>
          <ul className="space-y-2 font-body text-sm text-ink/80">
            <li>
              <b className="text-amber-900">Hazy IPA is the modern wave.</b> It is the fastest-rising
              new-wave style, well ahead of the next.
            </li>
            <li>
              <b className="text-amber-900">IPA leads, but not alone.</b> American IPA and Pale Ale top
              the list, with a strong middle of sessionable and classic European styles: Saison,
              Witbier, Blonde.
            </li>
            <li>
              <b className="text-amber-900">Citra and Cascade run neck and neck.</b> The classic
              American C-hops still outrank the newer varieties.
            </li>
            <li>
              <b className="text-amber-900">Clean American ale yeast dominates.</b> US-05 style strains
              carry close to a quarter of recipes; hazy strains are emerging but still niche.
            </li>
            <li>
              <b className="text-amber-900">Adjuncts are getting adventurous.</b> Orange peel, vanilla,
              grapefruit, hibiscus, honey and lime are showing up, alongside seltzers, fruited sours
              and the odd Brut IPA.
            </li>
          </ul>
        </SectionCard>

        {/* style vitals — ABV */}
        <SectionCard title="Strength by style · ABV %" tone="teal">
          <p className="mb-3 text-xs text-ink/60">
            Bar = 10th to 90th percentile spread. Tick = median. Dot = typical colour.
          </p>
          <StyleRangeChart rows={styleRows('abv', 12)} unit="%" ariaLabel="Median ABV percent by style" />
        </SectionCard>

        {/* style vitals — IBU */}
        <SectionCard title="Bitterness by style · IBU">
          <p className="mb-3 text-xs text-ink/60">Same twelve styles, bitterness spread and median.</p>
          <StyleRangeChart rows={styleRows('ibu', 12)} unit="" ariaLabel="Median IBU by style" />
        </SectionCard>

        {/* hops */}
        <SectionCard title="Most-used hops">
          <p className="mb-3 text-xs text-ink/60">
            From the {fmt(meta.ingredientRecipeCount)} recipes with full ingredient data.
          </p>
          <HBarChart data={toBars(hops.top, 12)} ariaLabel="Most-used hops by recipe count" />
        </SectionCard>

        {/* pairings */}
        <SectionCard title="Hops brewed together" tone="teal">
          <p className="mb-3 text-xs text-ink/60">How often two hops appear in the same recipe.</p>
          <HBarChart data={toBars(hops.pairings, 10)} ariaLabel="Most common hop pairings" />
        </SectionCard>

        {/* fermentables + yeasts */}
        <div className="grid gap-6 md:grid-cols-2">
          <SectionCard title="Fermentables">
            <HBarChart data={toBars(ferments.top, 10)} ariaLabel="Most-used fermentables" />
          </SectionCard>
          <SectionCard title="Yeasts">
            <HBarChart data={toBars(yeasts.top, 10)} ariaLabel="Most-used yeasts" />
          </SectionCard>
        </div>
      </div>

      {/* aggregate-only note */}
      <p className="mt-8 border-t border-amber-200 pt-4 font-body text-[0.7rem] leading-relaxed text-ink/50">
        Figures shown are aggregate statistics: derived values such as median ABV and typical
        ingredient usage, computed across many brewing recipes. They are not reproductions of any
        individual recipe. Styles are classified against the BJCP 2015 style guidelines.
      </p>
    </main>
  );
}
