/**
 * build-analytics.ts — build-time ETL for the recipe analytics feature.
 *
 * Pipeline (mirrors Beer Analytics' three stages, but reuses THIS repo's
 * own tested brewing libs instead of reimplementing the math):
 *
 *   1. PARSE      BeerXML files            -> raw recipe objects
 *   2. ENRICH     compute OG/FG/ABV/IBU/SRM (ibu.ts, srm.ts) + infer BJCP
 *                 style (styleCompliance.ts, bjcpStyles.ts)
 *   3. AGGREGATE  percentiles (IQR-trimmed), hop popularity + pairings,
 *                 fermentable/yeast usage -> public/analytics/*.json
 *
 * Run: `npm run build:analytics`. Output is static JSON consumed client-side.
 * No network, no server — safe for `output: 'export'` on GitHub Pages.
 */
import { XMLParser } from 'fast-xml-parser';
import { parse as parseCsv } from 'csv-parse/sync';
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { calculateIbu, type HopAddition } from '../src/lib/ibu';
import { calculateSrm, type SrmGrainItem } from '../src/lib/srm';
import { checkStyleCompliance, type RecipeStats } from '../src/lib/styleCompliance';
import { BJCP_STYLES, type BjcpStyleRange } from '../src/lib/bjcpStyles';

/**
 * Style reference for inference. Prefer the full official BJCP 2015 set
 * (100 styles, generated by scripts/extract-bjcp2015.mjs) when present;
 * otherwise fall back to the app's curated in-repo list. Kept separate
 * from src/lib/bjcpStyles.ts so the live style-check UI is unaffected.
 */
function loadStyles(root: string): BjcpStyleRange[] {
  const path = join(root, 'data/reference/bjcp2015-styles.json');
  if (existsSync(path)) {
    const full = JSON.parse(readFileSync(path, 'utf8')) as BjcpStyleRange[];
    if (full.length) return full;
  }
  return BJCP_STYLES;
}

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const RECIPES_DIR = join(ROOT, 'data/recipes');
const OUT_DIR = join(ROOT, 'public/analytics');
const STYLES = loadStyles(ROOT);

const parser = new XMLParser({ ignoreAttributes: true, parseTagValue: true });
const asArray = <T>(x: T | T[] | undefined): T[] => (x == null ? [] : Array.isArray(x) ? x : [x]);
const num = (x: unknown): number | null => {
  if (x === '' || x == null) return null;
  const n = Number(x);
  return Number.isFinite(n) ? n : null;
};
/** BeerXML gravities may arrive as SG (1.065) or as integer points (1065). */
const normalizeSg = (v: number | null): number | null =>
  v == null ? null : v > 100 ? v / 1000 : v;

interface Recipe {
  id: string;
  source: string;
  name: string;
  batchL: number;
  og: number;
  fg: number;
  abv: number;
  ibu: number;
  srm: number;
  style: string; // inferred
  hops: { name: string; use: string }[];
  ferms: { name: string }[];
  yeasts: { name: string }[];
}

// ---- 1. PARSE + 2. ENRICH -------------------------------------------------
function loadRecipe(xml: string, source: string, id: string): Recipe | null {
  const r = parser.parse(xml)?.RECIPES?.RECIPE;
  if (!r) return null;

  const batchL = num(r.BATCH_SIZE) ?? 20;
  const og = normalizeSg(num(r.EST_OG) ?? num(r.OG)) ?? 1.05;

  // FG: prefer stated; else estimate from yeast attenuation (BeerXML %).
  const yeasts = asArray<any>(r.YEASTS?.YEAST);
  const attenuation = (num(yeasts[0]?.ATTENUATION) ?? 75) / 100;
  let fg = normalizeSg(num(r.EST_FG) ?? num(r.FG));
  // Reject implausible FG (missing, <=1, or >= OG which would yield negative
  // ABV) and estimate from attenuation instead — his validate_and_fix step.
  if (fg == null || fg <= 1 || fg >= og) fg = +(og - (og - 1) * attenuation).toFixed(4);

  const abv = +Math.max(0, (og - fg) * 131.25).toFixed(2);

  // IBU: recompute from the hop bill (DIY Dog's stated IBU field is unreliable).
  // Only boil-side additions contribute bitterness; dry hops are excluded.
  const allHops = asArray<any>(r.HOPS?.HOP);
  const boilHops: HopAddition[] = allHops
    .filter((h) => /boil|first wort|mash/i.test(String(h.USE ?? 'Boil')))
    .map((h) => ({
      name: String(h.NAME ?? ''),
      alphaAcidPercent: num(h.ALPHA) ?? 0,
      weightG: (num(h.AMOUNT) ?? 0) * 1000, // BeerXML amount is kg
      boilTimeMinutes: Math.min(num(h.TIME) ?? 60, 120),
    }));
  const ibu = +calculateIbu(boilHops, og, batchL).totalIbu.toFixed(1);

  // SRM: from the grain bill (BeerXML fermentable COLOR is in Lovibond).
  const ferms = asArray<any>(r.FERMENTABLES?.FERMENTABLE);
  const grainBill: SrmGrainItem[] = ferms.map((f) => ({
    weightKg: num(f.AMOUNT) ?? 0,
    colorLovibond: num(f.COLOR) ?? 0,
  }));
  // Prefer computing SRM from grain colors (reuses the repo's Morey math).
  // Some exports (e.g. DIY Dog) strip per-malt colors to 0 but keep a
  // recipe-level estimate — fall back to that so SRM isn't lost.
  let srm = +calculateSrm(grainBill, batchL).toFixed(1);
  if (srm === 0) srm = num(r.EST_COLOR) ?? num(r.COLOR) ?? 0;
  // A "color" over ~60 is almost certainly EBC, not SRM (SRM tops out ~40 for
  // pitch black). Convert so the darkest stout doesn't read as SRM 152.
  if (srm > 60) srm = +(srm / 1.97).toFixed(1);

  const style = inferStyle({ og, fg, ibu, srm, abvPercent: abv });

  return {
    id: `${source}:${id}`,
    source,
    name: String(r.NAME ?? id),
    batchL,
    og,
    fg,
    abv,
    ibu,
    srm,
    style,
    hops: allHops.map((h) => ({ name: String(h.NAME ?? ''), use: String(h.USE ?? '') })),
    ferms: ferms.map((f) => ({ name: String(f.NAME ?? '') })),
    yeasts: yeasts.map((y) => ({ name: String(y.NAME ?? '') })),
  };
}

/** Nearest BJCP style: most parameters in range, tie-broken by closeness. */
function inferStyle(stats: RecipeStats): string {
  let best = 'Unclassified';
  let bestScore = -1;
  let bestDist = Infinity;
  for (const style of STYLES) {
    const res = checkStyleCompliance(stats, style);
    const dist = rangeDistance(stats, style);
    if (res.parametersInRange > bestScore || (res.parametersInRange === bestScore && dist < bestDist)) {
      best = style.name;
      bestScore = res.parametersInRange;
      bestDist = dist;
    }
  }
  return bestScore >= 3 ? best : 'Unclassified';
}
function rangeDistance(s: RecipeStats, style: BjcpStyleRange): number {
  const d = (v: number, r: { min: number; max: number }) =>
    v < r.min ? r.min - v : v > r.max ? v - r.max : 0;
  // Normalize each axis so gravity points don't get swamped by IBU units.
  return (
    d(s.og, style.og) * 1000 +
    d(s.ibu, style.ibu) +
    d(s.srm, style.srm) +
    d(s.abvPercent, style.abvPercent)
  );
}

// ================================================================
// 🟡 ANKUR OWNS THIS — ingredient normalization (the quality gate).
// Collapses spelling/format variants to one canonical name so
// "top hops" and pairings aren't fragmented. The crude default
// below works; your brewing judgment makes it good. Consider:
//  - Should "First Gold" and "Goldings" merge, or stay distinct?
//  - How to treat blends ("Falconer's Flight") and extracts?
//  - Fuzzy-match aggressiveness vs. false merges.
// See src/lib/hopVarieties.ts for the canonical variety list you
// could match against.
// ================================================================
function normalizeHop(raw: string): string {
  return raw
    .toLowerCase()
    .replace(/\s*\(.*?\)\s*/g, ' ') // drop "(US)"
    .replace(/\b(us|uk|nz|au|de|extract|leaf|pellet)\b/g, '')
    .replace(/[^a-z ]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

// ---- 3. AGGREGATE ---------------------------------------------------------
const percentile = (xs: number[], p: number): number | null => {
  const s = xs.filter((v) => v != null && Number.isFinite(v)).sort((a, b) => a - b);
  if (!s.length) return null;
  const i = (s.length - 1) * p;
  const lo = Math.floor(i);
  const hi = Math.ceil(i);
  return +(s[lo] + (s[hi] - s[lo]) * (i - lo)).toFixed(1);
};
/** IQR fence — the "remove_outliers" step, so one typo recipe can't skew a style. */
const trimOutliers = (xs: number[]): number[] => {
  const q1 = percentile(xs, 0.25);
  const q3 = percentile(xs, 0.75);
  if (q1 == null || q3 == null) return xs;
  const fence = 1.5 * (q3 - q1);
  return xs.filter((v) => v >= q1 - fence && v <= q3 + fence);
};
const dist = (xs: (number | null)[]) => {
  const clean = trimOutliers(xs.filter((v): v is number => v != null));
  return { p10: percentile(clean, 0.1), p50: percentile(clean, 0.5), p90: percentile(clean, 0.9) };
};

/**
 * Ingest recipe-level metrics from a CSV (e.g. the Brewer's Friend export).
 *
 * AGGREGATE-ONLY, by design: we read ONLY Style + numeric vitals and drop
 * Name/URL/UserId entirely, so no identifying or copyrightable recipe text
 * ever enters the pipeline. These rows carry no ingredient data, so they
 * strengthen style distributions but never appear in hop/fermentable/yeast
 * rankings. The raw CSV lives in gitignored data/private/ and is never
 * committed — only the derived aggregate JSON is. Read as latin1 so stray
 * non-UTF8 bytes in (discarded) names can't crash the parse.
 */
function loadCsvRecipes(path: string, source: string): Recipe[] {
  const rows = parseCsv(readFileSync(path, 'latin1'), {
    columns: true,
    skip_empty_lines: true,
    relax_quotes: true,
    relax_column_count: true,
    on_record: (rec) => rec, // keep as-is; we pick fields explicitly below
  }) as Record<string, string>[];

  const out: Recipe[] = [];
  let skipped = 0;
  for (const row of rows) {
    // Only trust Specific-Gravity rows (Plato rows would misread OG/FG).
    if ((row['SugarScale'] ?? '').trim() !== 'Specific Gravity') {
      skipped++;
      continue;
    }
    const og = normalizeSg(num(row['OG']));
    const fg = normalizeSg(num(row['FG']));
    const abv = num(row['ABV']);
    const ibu = num(row['IBU']);
    const srm = num(row['Color']);
    // Need the full vital set (and a sane OG) to place a recipe in a style.
    if (og == null || og < 1.02 || og > 1.2 || abv == null || ibu == null || srm == null) {
      skipped++;
      continue;
    }
    const style = inferStyle({ og, fg: fg ?? og, ibu, srm, abvPercent: abv });
    out.push({
      id: `${source}:${out.length}`,
      source,
      name: '', // deliberately discarded
      batchL: num(row['Size(L)']) ?? 20,
      og,
      fg: fg ?? og,
      abv,
      ibu,
      srm,
      style,
      hops: [],
      ferms: [],
      yeasts: [],
    });
  }
  console.log(`[analytics] ${source}: ${out.length} recipes ingested (${skipped} skipped: non-SG/incomplete)`);
  return out;
}

function main() {
  if (!existsSync(RECIPES_DIR)) {
    console.warn(`[analytics] no recipes dir at ${RECIPES_DIR} — skipping (nothing to build).`);
    return;
  }
  mkdirSync(OUT_DIR, { recursive: true });

  // Walk data/recipes/<source>/*.xml
  const recipes: Recipe[] = [];
  for (const source of readdirSync(RECIPES_DIR)) {
    const dir = join(RECIPES_DIR, source);
    let files: string[] = [];
    try {
      files = readdirSync(dir).filter((f) => f.toLowerCase().endsWith('.xml'));
    } catch {
      continue; // not a directory (e.g. provenance.json)
    }
    for (const f of files) {
      try {
        const rec = loadRecipe(readFileSync(join(dir, f), 'utf8'), source, f.replace(/\.xml$/i, ''));
        if (rec) recipes.push(rec);
      } catch (e) {
        console.warn(`[analytics] skipped ${source}/${f}: ${(e as Error).message}`);
      }
    }
  }

  // Aggregate-only CSV sources (gitignored data/private/*recipes*.csv).
  // These add statistical weight to STYLE distributions only — no ingredients.
  const PRIVATE_DIR = join(ROOT, 'data/private');
  if (existsSync(PRIVATE_DIR)) {
    for (const f of readdirSync(PRIVATE_DIR)) {
      if (!/recipes?.*\.csv$/i.test(f)) continue; // skip the style lookup CSV
      const source = f.replace(/\.csv$/i, '').replace(/-recipes?$/i, '');
      try {
        recipes.push(...loadCsvRecipes(join(PRIVATE_DIR, f), source));
      } catch (e) {
        console.warn(`[analytics] CSV ${f} failed: ${(e as Error).message}`);
      }
    }
  }

  // Per-style metric distributions
  const byStyle = new Map<string, Recipe[]>();
  for (const r of recipes) byStyle.set(r.style, [...(byStyle.get(r.style) ?? []), r]);
  const styles = [...byStyle.entries()]
    .map(([style, rs]) => ({
      style,
      count: rs.length,
      og: dist(rs.map((r) => r.og)),
      abv: dist(rs.map((r) => r.abv)),
      ibu: dist(rs.map((r) => r.ibu)),
      srm: dist(rs.map((r) => r.srm)),
    }))
    .sort((a, b) => b.count - a.count);

  // Hop popularity (normalized) + co-occurrence pairings
  const hopCount = new Map<string, number>();
  const pairCount = new Map<string, number>();
  for (const r of recipes) {
    const uniq = [...new Set(r.hops.map((h) => normalizeHop(h.name)).filter(Boolean))];
    for (const h of uniq) hopCount.set(h, (hopCount.get(h) ?? 0) + 1);
    for (let i = 0; i < uniq.length; i++)
      for (let j = i + 1; j < uniq.length; j++) {
        const key = [uniq[i], uniq[j]].sort().join(' + ');
        pairCount.set(key, (pairCount.get(key) ?? 0) + 1);
      }
  }
  const topN = (m: Map<string, number>, n: number) =>
    [...m.entries()].sort((a, b) => b[1] - a[1]).slice(0, n).map(([name, count]) => ({ name, count }));

  // Fermentable + yeast usage
  const fermCount = new Map<string, number>();
  const yeastCount = new Map<string, number>();
  for (const r of recipes) {
    for (const f of new Set(r.ferms.map((x) => x.name.trim()).filter(Boolean))) fermCount.set(f, (fermCount.get(f) ?? 0) + 1);
    for (const y of new Set(r.yeasts.map((x) => x.name.trim()).filter(Boolean))) yeastCount.set(y, (yeastCount.get(y) ?? 0) + 1);
  }

  // Per-source counts (total, and how many carry ingredient data).
  const sourceCounts: Record<string, { recipes: number; withIngredients: number }> = {};
  for (const r of recipes) {
    const s = (sourceCounts[r.source] ??= { recipes: 0, withIngredients: 0 });
    s.recipes++;
    if (r.hops.length || r.ferms.length) s.withIngredients++;
  }
  const ingredientRecipeCount = recipes.filter((r) => r.hops.length || r.ferms.length).length;

  const generatedAtIso = process.env.BUILD_TIME ?? null; // avoid nondeterminism unless provided
  writeFileSync(join(OUT_DIR, 'index.json'), JSON.stringify({
    generatedAt: generatedAtIso,
    recipeCount: recipes.length,
    ingredientRecipeCount,
    styleCount: styles.length,
    sources: [...new Set(recipes.map((r) => r.source))],
    sourceCounts,
  }, null, 2));
  writeFileSync(join(OUT_DIR, 'styles.json'), JSON.stringify(styles, null, 2));
  writeFileSync(join(OUT_DIR, 'hops.json'), JSON.stringify({ top: topN(hopCount, 30), pairings: topN(pairCount, 20) }, null, 2));
  writeFileSync(join(OUT_DIR, 'fermentables.json'), JSON.stringify({ top: topN(fermCount, 30) }, null, 2));
  writeFileSync(join(OUT_DIR, 'yeasts.json'), JSON.stringify({ top: topN(yeastCount, 30) }, null, 2));

  // ---- report -------------------------------------------------------------
  console.log(`[analytics] ${recipes.length} recipes -> ${styles.length} styles`);
  console.log('\nTOP INFERRED STYLES  (count | ABV p50 | IBU p50 | SRM p50):');
  for (const s of styles.slice(0, 10))
    console.log(`  ${String(s.count).padStart(3)}   ${String(s.abv.p50 ?? '-').padStart(5)}%   ${String(s.ibu.p50 ?? '-').padStart(5)} IBU   ${String(s.srm.p50 ?? '-').padStart(4)} SRM   ${s.style}`);
  console.log('\nTOP HOPS:');
  for (const { name, count } of topN(hopCount, 8)) console.log(`  ${String(count).padStart(3)}   ${name}`);
  console.log('\nTOP PAIRINGS:');
  for (const { name, count } of topN(pairCount, 6)) console.log(`  ${String(count).padStart(3)}   ${name}`);
  console.log(`\n[analytics] wrote 5 files to public/analytics/`);
}

main();
